default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: thuy2495
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: project
  
  
production:
  <<: *default
  database: project
  username: same_app
  password: <%= ENV['LOGIN_APP_DATABASE_PASSWORD'] %>
